/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCertificatesIndexRouteImport } from './routes/admin.certificates.index'
import { Route as AdminCertificatesIdRouteImport } from './routes/admin.certificates.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesIndexRoute = AdminCertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesIdRoute = AdminCertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin/certificates/$id': typeof AdminCertificatesIdRoute
  '/admin/certificates/': typeof AdminCertificatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify': typeof VerifyIndexRoute
  '/admin/certificates/$id': typeof AdminCertificatesIdRoute
  '/admin/certificates': typeof AdminCertificatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/upload': typeof AdminUploadRoute
  '/verify/$id': typeof VerifyIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin/certificates/$id': typeof AdminCertificatesIdRoute
  '/admin/certificates/': typeof AdminCertificatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/verify/$id'
    | '/verify/'
    | '/admin/certificates/$id'
    | '/admin/certificates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/verify/$id'
    | '/verify'
    | '/admin/certificates/$id'
    | '/admin/certificates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/dashboard'
    | '/admin/upload'
    | '/verify/$id'
    | '/verify/'
    | '/admin/certificates/$id'
    | '/admin/certificates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyIdRoute: typeof VerifyIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates/': {
      id: '/admin/certificates/'
      path: '/certificates'
      fullPath: '/admin/certificates/'
      preLoaderRoute: typeof AdminCertificatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates/$id': {
      id: '/admin/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/admin/certificates/$id'
      preLoaderRoute: typeof AdminCertificatesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminCertificatesIdRoute: typeof AdminCertificatesIdRoute
  AdminCertificatesIndexRoute: typeof AdminCertificatesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminCertificatesIdRoute: AdminCertificatesIdRoute,
  AdminCertificatesIndexRoute: AdminCertificatesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyIdRoute: VerifyIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
